version: '2'

services:
  nginx:
    build:
      context: .nginx/
      dockerfile: Dockerfile
    links:
      - node1:node1
    depends_on:
      - node1
    ports:
      - "3456:3456"
    networks:
      - email-network
    
  node1:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    ports:
      - "3456"
    environment:
      - INSTANCE=node1
    networks:
      - email-network

networks:
  email-network:
    driver: bridge