version: '2'

services:
  authservice:
    environment:
      - NODE_ENV=prod
      - EMAIL_USERNAME=valindo.godinho@zoho.com
      - EMAIL_PASSWORD=p.hf2!P3yQfp7nX
      - EMAIL_HOST=smtp.zoho.com
      - EMAIL_PORT=465