version: "2"
services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    depends_on:
      - db
    links:
      - db
    ports:
      - "3001:3000"
    environment:
      - INSTANCE=authservice
    networks:
      - authservice_default
  db:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=wakanda_auth_service
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=wakanda_auth_db
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./dbdata:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    expose:
      - "5432"
    networks:
      - authservice_default

networks:
  authservice_default:
    driver: bridge
