version: "2"
services:
  authservice:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    depends_on:
      - db
    links:
      - db
    ports:
      - "3001:3000"
    environment:
      - INSTANCE=authservice
      - AUTH_SERVICE_BASEPATH=${ENV_AUTH_SERVICE_BASEPATH}
      - CONSENT_SERVICE_BASEPATH=${ENV_CONSENT_SERVICE_BASEPATH}
      - CONSENT_SERVICE_HOST=${ENV_CONSENT_SERVICE_HOST}
      - CONSENT_SERVICE_ENDPOINT_URI=${ENV_CONSENT_SERVICE_ENDPOINT_URI}
      - DB_USERNAME=${ENV_DB_USERNAME}
      - DB_PASSWORD=${ENV_DB_PASSWORD}
      - DB_NAME=${ENV_DB_NAME}
      - DB_HOST=${ENV_DB_HOST}
      - DB_PORT=${ENV_DB_PORT}
      - SMS_SERVICE_ACTIVE=false
      - SMS_API_ENDPOINT=${ENV_SMS_API_ENDPOINT}
      - SMS_PASSPHRASE=${ENV_SMS_PASSPHRASE}
      - SMS_APP_ID=${ENV_SMS_APP_ID}
      - SMS_APP_SECRET=${ENV_SMS_APP_SECRET}
      - AUTH_CLIENT_ID=${ENV_AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${ENV_AUTH_CLIENT_SECRET}
      - CONSENT_CLIENT_ID=${ENV_CONSENT_CLIENT_ID}
      - CONSENT_CLIENT_SECRET=${ENV_CONSENT_CLIENT_SECRET}
      - AUTHENTICATION_ACTIVE=${ENV_AUTHENTICATION_ACTIVE}
    networks:
      - authservice_default
  db:
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${ENV_DB_USERNAME}
      - POSTGRES_PASSWORD=${ENV_DB_PASSWORD}
      - POSTGRES_DB=${ENV_DB_NAME}

    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./dbdata:/docker-entrypoint-initdb.d/
    ports:
      - "5433:5432"
    # expose:
    #   - "5432"
    networks:
      - authservice_default

networks:
  authservice_default:
    driver: bridge
