version: '2'

services:
  node1:
    environment:
      - NODE_ENV=test
      - SENDERS_EMAIL=valindo.godinho@zoho.com
      - SENDERS_NAME=Globe Telecom
      - EMAIL_USERNAME=valindo.godinho@zoho.com
      - EMAIL_PASSWORD=p.hf2!P3yQfp7nX
      - EMAIL_HOST=smtp.zoho.com
      - EMAIL_PORT=465
      - PORT=3456