version: "2"

services:
  redis:
    image: redis
    container_name: devicetac
    expose:
      - 6379
    networks:
      - app-network
  nginx:
    build:
      context: .nginx/
      dockerfile: Dockerfile
    links:
      - devicedetailnode:devicedetailnode
    depends_on:
      - devicedetailnode
    ports:
      - "5558:5558"
    networks:
      - app-network

  devicedetailnode:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    links:
      - redis:redis
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    ports:
      - "5558"
    environment:
      - INSTANCE=devicedetailnode
    networks:
      - app-network

networks:
  app-network:
    driver: bridge