version: "2"

services:
  nginx:
    build:
      context: .nginx/
      dockerfile: Dockerfile
    links:
      - bypassnode:bypassnode
    depends_on:
      - bypassnode
    ports:
      - "5556:5556"
    networks:
      - app-network

  bypassnode:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    ports:
      - "5556"
    environment:
      - INSTANCE=bypassnode
    networks:
      - app-network

networks:
  app-network:
    driver: bridge