version: "3"

services:
  # nginx:
  #   build:
  #     context: .docker/
  #     dockerfile: Dockerfile
  #   links:
  #     - consentms:consentms
  #   depends_on:
  #     - consentms
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - consentserivce_default

  consentms:
    container_name: consentservice
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    # depends_on:
    #   - db
    # links:
    #   - db
    ports:
      - "3002:3002"
    environment:
      - INSTANCE=consentms
      - AUTH_SERVICE_BASEPATH=${ENV_AUTH_SERVICE_BASEPATH}
      - CONSENT_SERVICE_BASEPATH=${CONSENT_SERVICE_BASEPATH}
      - DB_USERNAME=${ENV_DB_USERNAME}
      - DB_PASSWORD=${ENV_DB_PASSWORD}
      - DB_NAME=${ENV_DB_NAME}
      - DB_HOST=${ENV_DB_HOST}
      - DB_PORT=${ENV_DB_HOST}
    networks:
      - consentserivce_default
  # db:
  #   restart: always
  #   image: postgres:10
  #   environment:
  #   - POSTGRES_USER=wakanda_consent_user
  #   - POSTGRES_PASSWORD=12345
  #   - POSTGRES_DB=wakanda_consent
  #   volumes:
  #   - ./postgres-data/postgres:/var/lib/postgresql/data
  #   - ./dbdata:/docker-entrypoint-initdb.d/
  #   ports:
  #   - "5432:5434"
  #   expose:
  #   - "5434"

networks:
  consentserivce_default:
    external:
      name: auth-service_authservice_default
