version: "3"

services:
  # nginx:
  #   build:
  #     context: .docker/
  #     dockerfile: Dockerfile
  #   links:
  #     - consentms:consentms
  #   depends_on:
  #     - consentms
  #   ports:
  #     - "3002:3002"
  #   networks:
  #     - consentserivce_default

  consentms:
    container_name: consentservice
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - $HOME/logs:/var/log
    depends_on:
      - dcms
    links:
      - dcms
    ports:
      - "3002:3002"
    environment:
      - INSTANCE=consentms
      - AUTH_SERVICE_BASEPATH=${ENV_AUTH_SERVICE_BASEPATH}
      - CONSENT_SERVICE_BASEPATH=${ENV_CONSENT_SERVICE_BASEPATH}
      - DB_USERNAME=${ENV_DB_USERNAME}
      - DB_PASSWORD=${ENV_DB_PASSWORD}
      - DB_NAME=${ENV_DB_NAME}
      - DB_HOST=${ENV_DB_HOST}
      - DB_PORT=${ENV_DB_PORT}
      - AUTH_CLIENT_ID=${ENV_AUTH_CLIENT_ID}
      - AUTH_CLIENT_SECRET=${ENV_AUTH_CLIENT_SECRET}
      - CONSENT_CLIENT_ID=${ENV_CONSENT_CLIENT_ID}
      - CONSENT_CLIENT_SECRET=${ENV_CONSENT_CLIENT_SECRET}
      - AUTHENTICATION_ACTIVE=${ENV_AUTHENTICATION_ACTIVE}
    networks:
      - consentserivce_default
  dcms:
    container_name: dcms
    restart: always
    image: postgres:10
    environment:
      - POSTGRES_USER=${ENV_DB_USERNAME}
      - POSTGRES_PASSWORD=${ENV_DB_PASSWORD}
      - POSTGRES_DB=${ENV_DB_NAME}
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
      - ./dbdata:/docker-entrypoint-initdb.d/
    ports:
      - "5434:5432"
    expose:
      - "5434"
    networks:
      - consentserivce_default

networks:
  consentserivce_default:
    external:
      name: auth-service_authservice_default
